#---Newlife game options---
#Sat Feb 21 18:26:19 EST 2026
ADDITIONAL_MALE_NPCS=0
USE_CUSTOM_NPCS=true
ADVANCED_SECRET=false
ALLOW_LACTATION=true
BLOCKED_NAMES=
USE_DARK_THEME=true
ALLOW_ANAL_SEX=true
ALLOW_ABORTION=false
ALLOW_AUTO_SEX=false
TEXT_FONT_SIZE=20
UNLOCK_OLDER_AGES=false
DEFAULT_MALE_NAME=
CLOTHING_TEXT_FONT_SIZE=16
ALLOW_AUTO_SEX_VIRGINITY_LOSS=false
RELAX_OUTFIT_RESTRICTIONS=false
ALLOW_LOVE_DECAY=true
ADDITIONAL_FEMALE_NPCS=0
QUICK_START=false
ALLOW_CUSTOM_SCENE_TESTING=true
QUICKSTART_RANDOMISATION=TWEAKED
AUTO_OUTFIT_LIMIT=10
COMPLETED_GAME=false
ACTIVATE_VOWS_PRE_WEDDING=false
DEFAULT_FEMALE_NAME=
